# Utiliza una imagen base de Python adecuada
FROM python:3.11.3

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia los archivos de tu aplicación al contenedor
COPY . /app

# Instala las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Expone el puerto en el que se ejecuta Streamlit
EXPOSE 8501

# Comando para ejecutar la aplicación de Streamlit
CMD ["python", "app.py"]




# Paso 3: Construir y ejecutar la imagen de Docker

#Una vez que hayas creado el Dockerfile, puedes construir la imagen de Docker utilizando el siguiente comando en la terminal:

#docker run -p 8501:8501 nombre-de-tu-imagen
